# Generated by Django 5.0.4 on 2024-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
